name: CI

on:
  pull_request:
    branches: [ "master" ]  
  workflow_dispatch:

jobs:

  build:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Build with Maven
        id: maven
        continue-on-error: true 
        working-directory: ${{ github.workspace }}/${{ github.head_ref }}
        run: mvn -B package --file pom.xml
        
      - name: Build with Gradle  
        id: gradle
        continue-on-error: true
        working-directory: ${{ github.workspace }}/${{ github.head_ref }}
        run: gradlew build
      
      - name: Check build result
        if: ${{ contains(steps.maven.outcome, 'failure') && contains(steps.gradle.outcome, 'failure') }}
        run: exit 1

  branch:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v2
      - name: Check branch directory
        shell: bash
        run: |
          branch_name="${{ github.head_ref }}"
          changes="$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -v '^$')"
          
          if [[ "$changes" != *"/$branch_name/"* ]]; then
            echo "Changes found outside of /$branch_name/ directory"
            exit 1
          fi

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: '.github/google_checks.xml'
          reporter: 'github-pr-check'
          # level: error
          fail_on_error: true
