# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "master" ]  
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Build with Maven
        id: maven
        continue-on-error: true 
        run: mvn -B package --file pom.xml
        
      - name: Build with Gradle  
        id: gradle
        continue-on-error: true
        run: ./gradlew build
        
      - name: Check build result
        if: ${{ contains(steps.*.outcome,'failure') }}
        run: exit 1

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: '.github/google_checks.xml'
          reporter: 'github-pr-check'
